# -*- coding: utf-8 -*-
"""day10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3g5muvet24ZwBt953tEjp24CwOrGjIb
"""

import numpy as np
import matplotlib.pyplot as plt
print('done')

arr=plt.imread("/car1.jpg")
print(arr)

car_arr = arr.copy()

plt.imshow(car_arr)

car_arr.shape

while True:
  a= np.random.randint(1,255,(5,5,3))
  plt.imshow(a)
  plt.show()
  import time
  display(clear=True)
  time.sleep(2)

a = np.random.randint(1,255,(4,4,3))
a

final_arr= np.split(a,2)
len(final_arr)

plt.imshow(a)

plt.imshow(final_arr[1])

arr1= np.split(a,2,axis=1)

len(arr1)

arr1

a.shape

arr_3_part= np.split(a,3,axis=2)

arr_3_part

plt.imshow(a)

len(arr_3_part)

plt.imshow(arr_3_part[0])

car_arr.shape

plt.imshow(np.split(car_arr,4,axis=0)[0])

plt.imshow(np.split(car_arr,4,axis=0)[1])

plt.imshow(np.split(car_arr,4,axis=0)[2])

plt.imshow(np.split(car_arr,4,axis=0)[3])

car_arr.shape

plt.imshow(car_arr[:,:60,:])

plt.imshow(car_arr[:,60:60*2,:])

plt.imshow(car_arr[:,60*2:60*3,:])

plt.imshow(car_arr[:,60*3:60*4,:])

plt.imshow(car_arr[:,60*4:,:])

plt.imshow(np.split(car_arr,6,axis=1)[2])

arr2= np.random.randint(1,500,(4,4))
arr2

np.where(arr2>200,'High Sales',arr2)

np.clip(arr2,100,300)# remaove outlier and replace it by lower and upper bound

az=np.random.randint(1,10,(1,1,5))
ab=np.random.randint(1,10,(5,5,5))
print(az)

print('\n.........\n')
print(ab)
c=az+ab
print('\n.........\n')
print(c)

#broadcasting

d=az*ab
print(d)

import pandas as pd
pd.__version__

import random#faker module creates fake data

all_date=pd.date_range('01-01-2025','23-07-2025')
products =['chair','tables','laptop','Mobile Phone','Charger']
region=["East","West","North","South"]
data={'Order id ':range(1,1001),
      'Date':random.choices(all_date,k=1000),
      'Region Name':random.choices(region,k=1000),
      'Product Name':random.choices(products,k=1000),
      'Sales':np.random.randint(100,1000,1000),
      'Qty':np.random.randint(1,10,1000),
      'Profit':np.random.randint(-10000,10000,1000)}
table = pd.DataFrame(data)
table

table.head(10)

table.tail(10)

table.sample()

table.info()

table.columns

table.index

table.describe()

table.isna().value_counts()

table.isnull().value_counts()





















import krishna as