# -*- coding: utf-8 -*-
"""day 1 Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192V2T5hbUdQfX5KcmDMVdysnn5MVsk21
"""

# Int
a = 5678
print(a,type(a))

# Float
a = 4567.8765
print(a,type(a))

# pip install qrcode

import qrcode
img = qrcode.make('https://colab.research.google.com/drive/1mcwryu-5DRrBIAnZx-ezis0r7PrfmPBA?usp=sharing')
img.save('myqr.png')

# Complex
a = 456 + 8j
print(a,type(a))

# Int,float, Complex = Numerical

# Str, double, triple
a = 'Hello Python'
print(a,type(a))

poem = '''Twinkle twinkle little star
How I wonder what you are
Up above the world so high
Like a diamond in the sky
Twinkle twinkle little star
How I wonder what you are



Twinkle twinkle little star
How I wonder what you are
Up above the world so high
Like a diamond in the sky
Twinkle twinkle little star
How I wonder what you are'''


print(poem)

# tuple
a = (2,3434,5,5467)
print(a,type(a))

# tuple
a = (2,)
print(a,type(a))

# tuple
a = [2,3434,5,5467]
print(a,type(a))

a[2] = 4000

print(a)

a = (3,544,5,346,567)

print(a[3])

a[3] = 900

a = list(a)
a[3] = 900
a = tuple(a)
print(a)

std_id = [1,1,2,2,2,2,23,3,3,3,4,4,45]

print(std_id)

std_id = list(set(std_id))
print(std_id)

# dict:- key value pair datatype, # hash

a = {'Name':'Aman','Age':23,'Address':'Delhi'}
print(a,type(a))

a['Address'] = 'Noida/Gr Noida'

print(a)

a['Name'] = 'Aman Kumar'

print(a)

data = {'Region':['West','East','North','South'],
        'Sales':[345,546,453,456],
        'Profit':[120,200,90,78]}

print(data)

import pandas as pd

table = pd.DataFrame(data)
table

table

a = True
print(a,type(a))

# #int,float, complex
# str, tuple, list
# set, dict,
# # bool

# salary = 56789

# >= 50: manager
# >= 30: Jr manager
# >= 20: Executive
# Intern

salary = 27800
if salary >= 50000:
  print('Manager')
elif salary >= 30000:
  print('Jr Manager')
elif salary >= 20000:
  print('Executive')
else:
  print('Intern')

import random
random.randint(10000,60000,5)

import numpy as np
database_salary = np.random.randint(10000,60000,5)

print(salary)

for i in database_salary:
  salary = i
  if salary >= 50000:
    print(i, 'Manager')
  elif salary >= 30000:
    print(i, 'Jr Manager')
  elif salary >= 20000:
    print(i, 'Executive')
  else:
    print(i, 'Intern')

import time
for i in range(20):
  print(time.asctime())
  time.sleep(1)
  display(clear= True)

import random
comp_choice = random.randint(1,10)
user_choice = int(input('Enter your Choice(1-10): '))

print(f'''
User choice: {user_choice}
Computer Choice: {comp_choice}''')

if user_choice == comp_choice:
  print('User Won, Comp Lose!!')
else:
  print('Better Luck next time!!')

user_attempts = 3
import random
for i in range(user_attempts):
  comp_choice = random.randint(1,10)
  user_choice = int(input('Enter your Choice(1-10): '))

  print(f'''
  User choice: {user_choice}
  Computer Choice: {comp_choice}''')

  if user_choice == comp_choice:
    print('User Won, Comp Lose!!')
  else:
    print('Better Luck next time!!')

Questions[1]

Questions = {1:'What is the capital of Australia?',
             2:'Who invented the telephone?',
             3:'Which planet is known as the Red Planet?',
             4:'In which year did India gain independence?',
             5:'What is the largest organ in the human body?'}

options = {1:'''A) Sydney
B) Melbourne
C) Canberra
D) Perth''',
           2:'''A) Albert Einstein
B) Isaac Newton
C) Alexander Graham Bell
D) Thomas Edison''',
           3:'''A) Earth
B) Venus
C) Jupiter
D) Mars''',
           4:'''A) 1945
B) 1946
C) 1947
D) 1950''',
           5:'''A) Liver
B) Brain
C) Skin
D) Heart'''}

win_ammount = 0

correct_op = ['C','C','D','C','C']

for i in range(1,len(Questions)+1):
  print(f'Question {i}: ',Questions[i])
  print(options[i])
  user_choice = input('Enter your choice: ').upper()

  correct_ans = correct_op[i-1]
  # print(correct_ans)
  if user_choice == correct_ans:
    win_ammount += 10000
    print('Correct Answer!!')
    print(end = '\n'*3)

  else:
    print('Better luck next time!!')
    break


print('Total Amount',win_ammount)

def say_hello(name):
  print(f'Hello {name},','how are you??')

say_hello('Mohan')

def vote(age):
  print('can Vote!!') if age >= 18 else print('can not Vote!!')

vote(3)

# pip install gTTS

def sound_box(paisa,platform = 'Paytm'):
    from gtts import gTTS
    text  = f'''{platform} par {paisa} rs Prapt hue.'''
    audio = gTTS(text)
    audio.save('paytm.mp3')

    import pygame as p
    p.init()

    music = p.mixer.Sound('paytm.mp3')
    music.play()

# pip install pygame

